TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := tn8

# Platform
TARGET_BOARD_PLATFORM := tegra
TARGET_BOARD_PLATFORM_GPU := kepler
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60

# Architecture
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a15

BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x001000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x001000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x050000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x2FAECC000
#BOARD_CACHEIMAGE_PARTITION_SIZE    := 0x0#UNKNOWN
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_PREBUILT_KERNEL := device/nvidia/shieldtablet/zImage

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/tegra-ehci.0/usb/gadget/lun%d/file"

# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_CUSTOM_BOOTIMG_MK :=  device/nvidia/shieldtablet/bootimg.mk

# TWRP specific build flags
TW_THEME := portrait_hdpi
BOARD_HAS_FLIPPED_SCREEN := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/pwm-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 162
TW_INCLUDE_CRYPTO := true
TW_MTP_DEVICE := "/dev/mtp_usb"
